language: d

d:
  - dmd
  - ldc

install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
  - sudo apt-get update
  - sudo apt-get update -q
  - sudo apt-get remove -y llvm-*
  - sudo apt-get install -y clang-6.0 libclang-6.0 libclang-6.0-dev llvm-6.0 llvm-6.0-dev liblld-6.0 liblld-6.0-dev

notifications:
  email: false

script: make
